Настройка маршрутизации
htmlacademy-react/210815-six-cities-5 pull request #4
Opened 2020-10-13 19:33 UTC by fraankee

2020-10-14 09:59 UTC, IArny requested changes

2020-10-14 09:59 UTC, IArny commented on public/index.html
> +  <script src="../bundle.js"></script>
а для чего `..`? бандл вроде как в той же папке лежит

2020-10-14 10:27 UTC, fraankee commented on public/index.html
> +  <script src="../bundle.js"></script>
хм.. добавила, потому что ошибка со страниц предложений, например /offers/1324, оттуда не находит бандл

2020-10-14 16:16 UTC, IArny commented on public/index.html
> +  <script src="../bundle.js"></script>
пропиши в теге head <base href="/" />

2020-10-15 07:54 UTC, fraankee commented on public/index.html
> +  <script src="../bundle.js"></script>
пасиб, не знала про такой тег) добавила

2020-10-15 08:26 UTC, merged